### ISSUE TITLE
Failing when copying files

### ISSUE THREAD

**Issue by mjstahl** [mjstahl/quick-react-demo#1]
```console
Error: ENOENT: no such file or directory, copyfile '/Users/mark/.npm/_npx/63813/lib/node_modules/quick-react-demo/index.html' -> '/Users/mark/Projects/JavaScript/hello-world/index.html'
    at Object.copyFileSync (fs.js:1724:3)
    at files.forEach.f (/Users/mark/.npm/_npx/63813/lib/node_modules/quick-react-demo/index.js:30:25)
    at Array.forEach (<anonymous>)
    at fs.mkdir (/Users/mark/.npm/_npx/63813/lib/node_modules/quick-react-demo/index.js:30:9)
    at FSReqWrap.oncomplete (fs.js:141:20)
```

**Comment by mjstahl** [comment]
Not sure what I am doing wrong at https://github.com/mjstahl/quick-react-demo/blob/master/index.js#L30
